from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
STRIP = SCRIPTS / "strip_ai_trailers.py"
SCAN = SCRIPTS / "scan_history.py"
INSTALL = SCRIPTS / "install_hook.py"
sys.path.insert(0, str(SCRIPTS))

from strip_ai_trailers import is_ai_identity, strip_message  # noqa: E402

HUMAN = "Co-authored-by: Jane Doe <jane@example.com>"
DIRTY = f"""feat: add login form

Explains why.

{HUMAN}
Co-authored-by: Claude <noreply@anthropic.com>
Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>
Co-authored-by: Codex <noreply@openai.com>
Co-authored-by: Cursor <cursoragent@cursor.com>
Made-with: Cursor
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>
Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>
Co-authored-by: aider (gpt-4o) <noreply@aider.chat>
\U0001F916 Generated with [Claude Code](https://claude.com/claude-code)
Generated with [Codex](https://openai.com/codex/).
https://claude.ai/code/session_0123
"""


def isolated_env(home: Path) -> dict[str, str]:
    env = {k: v for k, v in os.environ.items() if not k.startswith("GIT_")}
    env.update(
        HOME=str(home),
        GIT_CONFIG_NOSYSTEM="1",
        GIT_CONFIG_GLOBAL=str(home / "gitconfig"),
        GIT_AUTHOR_NAME="Kim User",
        GIT_AUTHOR_EMAIL="kim@example.com",
        GIT_COMMITTER_NAME="Kim User",
        GIT_COMMITTER_EMAIL="kim@example.com",
    )
    return env


class StripMessageTest(unittest.TestCase):
    def test_removes_ai_lines_and_keeps_human_trailer(self):
        clean, removed = strip_message(DIRTY)
        self.assertEqual(f"feat: add login form\n\nExplains why.\n\n{HUMAN}\n", clean)
        self.assertEqual(11, len(removed))

    def test_clean_message_is_untouched(self):
        text = "fix: typo\n\nBody line.\n\n\nSigned-off-by: Kim User <kim@example.com>\n"
        self.assertEqual((text, []), strip_message(text))

    def test_human_named_claude_is_kept(self):
        text = "docs: x\n\nCo-authored-by: Claude Dupont <claude.dupont@gmail.com>\n"
        self.assertEqual([], strip_message(text)[1])

    def test_vendor_employee_is_kept_but_vendor_agent_is_not(self):
        self.assertFalse(is_ai_identity("Jane", "jane@anthropic.com"))
        self.assertTrue(is_ai_identity("Claude", "claude@anthropic.com"))
        self.assertTrue(is_ai_identity("anything", "cursoragent@cursor.com"))
        self.assertTrue(is_ai_identity("dependabot[bot]", "49699333+dependabot[bot]@users.noreply.github.com"))
        self.assertFalse(is_ai_identity("Kim User", "kim@example.com"))

    def test_pr_footer_variants(self):
        body = "## Summary\n- change\n\nAssisted by Claude Code\nMade with Cursor\n_Generated by Copilot_\n"
        self.assertEqual("## Summary\n- change\n", strip_message(body)[0])


class StripCliTest(unittest.TestCase):
    def run_strip(self, *args: str, stdin: str = "") -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(STRIP), "--no-git-config", *args],
            input=stdin, capture_output=True, text=True, check=False,
        )

    def test_stdin_stdout(self):
        proc = self.run_strip(stdin=DIRTY)
        self.assertEqual(0, proc.returncode, proc.stderr)
        self.assertNotIn("anthropic", proc.stdout)
        self.assertIn(HUMAN, proc.stdout)

    def test_check_mode_exit_codes(self):
        self.assertEqual(1, self.run_strip("--check", stdin=DIRTY).returncode)
        self.assertEqual(0, self.run_strip("--check", stdin="fix: ok\n").returncode)

    def test_in_place_and_custom_pattern(self):
        with tempfile.TemporaryDirectory() as tmp:
            msg = Path(tmp) / "MSG"
            msg.write_text("chore: x\n\nPowered-Note: internal bot\n", encoding="utf-8")
            proc = self.run_strip(str(msg), "--pattern", r"^Powered-Note:")
            self.assertEqual(0, proc.returncode, proc.stderr)
            self.assertEqual("chore: x\n", msg.read_text(encoding="utf-8"))

    def test_bad_regex_is_usage_error(self):
        self.assertEqual(2, self.run_strip("--pattern", "(", stdin="x\n").returncode)


class GitRepoCase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        base = Path(self._tmp.name)
        (base / "home").mkdir()
        self.env = isolated_env(base / "home")
        self.repo = base / "repo"
        self.git("init", "-q", "-b", "main", str(self.repo), cwd=base)

    def tearDown(self):
        self._tmp.cleanup()

    def git(self, *args: str, cwd: Path | None = None, env: dict[str, str] | None = None) -> str:
        proc = subprocess.run(
            ["git", *args], cwd=cwd or self.repo, env=env or self.env,
            capture_output=True, text=True, check=False,
        )
        self.assertEqual(0, proc.returncode, proc.stderr)
        return proc.stdout

    def commit(self, message: str, env: dict[str, str] | None = None, *extra: str) -> None:
        name = f"f{len(list(self.repo.glob('f*')))}"
        (self.repo / name).write_text(name, encoding="utf-8")
        self.git("add", name)
        self.git("commit", "-q", "-m", message, *extra, env=env)

    def run_script(self, script: Path, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(script), "--repo", str(self.repo), *args],
            env=self.env, capture_output=True, text=True, check=False,
        )


class ScanHistoryTest(GitRepoCase):
    def test_clean_history_exits_zero(self):
        self.commit("feat: one")
        proc = self.run_script(SCAN, "--json")
        self.assertEqual(0, proc.returncode, proc.stdout + proc.stderr)
        report = json.loads(proc.stdout)
        self.assertTrue(report["clean"])
        self.assertEqual(1, report["commits_scanned"])
        self.assertEqual("HEAD --not --remotes", report["range"])

    def test_finds_trailer_and_ai_author(self):
        self.commit("feat: one")
        self.commit(f"feat: two\n\n{HUMAN}\nCo-authored-by: Claude <noreply@anthropic.com>")
        bot = dict(self.env, GIT_AUTHOR_NAME="Cursor Agent", GIT_AUTHOR_EMAIL="cursoragent@cursor.com")
        self.commit("feat: three", bot)
        proc = self.run_script(SCAN, "--json")
        self.assertEqual(1, proc.returncode, proc.stdout + proc.stderr)
        report = json.loads(proc.stdout)
        kinds = sorted((i["kind"], i["reason"]) for f in report["findings"] for i in f["issues"])
        self.assertEqual([("author", "ai-identity"), ("message", "ai-trailer")], kinds)
        self.assertEqual(2, len(report["findings"]))

    def test_default_range_is_unpushed_only(self):
        self.commit("feat: old\n\nCo-authored-by: Codex <noreply@openai.com>")
        remote = Path(self._tmp.name) / "remote.git"
        self.git("init", "-q", "--bare", str(remote))
        self.git("remote", "add", "origin", str(remote))
        self.git("push", "-q", "-u", "origin", "main")
        self.commit("feat: new")
        report = json.loads(self.run_script(SCAN, "--json").stdout)
        self.assertEqual("@{upstream}..HEAD", report["range"])
        self.assertTrue(report["clean"])
        self.assertEqual(1, self.run_script(SCAN, "--all").returncode)

    def test_annotated_tag_message_is_scanned_with_all(self):
        self.commit("feat: one")
        self.git("tag", "-a", "v1.0.0", "-m", "v1.0.0\n\n\U0001F916 Generated with Claude Code")
        report = json.loads(self.run_script(SCAN, "--all", "--json").stdout)
        self.assertEqual("v1.0.0", report["tags"][0]["tag"])

    def test_check_identity(self):
        self.assertEqual(0, self.run_script(SCAN, "--check-identity").returncode)
        self.env.update(GIT_AUTHOR_NAME="Claude", GIT_AUTHOR_EMAIL="noreply@anthropic.com")
        proc = self.run_script(SCAN, "--check-identity", "--json")
        self.assertEqual(1, proc.returncode)
        self.assertEqual("author", json.loads(proc.stdout)["issues"][0]["kind"])

    def test_empty_repo_is_clean(self):
        self.assertEqual(0, self.run_script(SCAN).returncode)

    def test_not_a_repo_is_error(self):
        with tempfile.TemporaryDirectory() as tmp:
            proc = subprocess.run([sys.executable, str(SCAN), "--repo", tmp], env=self.env,
                                  capture_output=True, text=True, check=False)
            self.assertEqual(2, proc.returncode)

    def test_msg_filter_cleanup_keeps_tree(self):
        self.commit("feat: one\n\nCo-authored-by: Claude <noreply@anthropic.com>")
        self.commit(f"feat: two\n\n{HUMAN}\nGenerated with [Codex](https://openai.com/codex/).")
        before = self.git("rev-parse", "HEAD^{tree}")
        self.git("branch", "clonamic-backup/main")
        env = dict(self.env, FILTER_BRANCH_SQUELCH_WARNING="1")
        self.git("filter-branch", "-f", "--msg-filter", f'"{sys.executable}" "{STRIP}" --quiet', "--", "HEAD", env=env)
        self.assertEqual(before, self.git("rev-parse", "HEAD^{tree}"))
        self.assertEqual(0, self.run_script(SCAN).returncode)
        self.assertIn(HUMAN, self.git("log", "-1", "--format=%B"))


class InstallHookTest(GitRepoCase):
    def test_install_strips_on_commit_and_uninstall(self):
        proc = self.run_script(INSTALL)
        self.assertEqual(0, proc.returncode, proc.stderr)
        self.commit(f"feat: hooked\n\n{HUMAN}\nCo-authored-by: Claude <noreply@anthropic.com>\nMade-with: Cursor")
        self.assertEqual(f"feat: hooked\n\n{HUMAN}\n", self.git("log", "-1", "--format=%B").rstrip("\n") + "\n")
        self.assertIn("installed", self.run_script(INSTALL, "--status").stdout)
        self.assertEqual(0, self.run_script(INSTALL, "--uninstall").returncode)
        hooks = self.repo / ".git" / "hooks"
        self.assertFalse((hooks / "commit-msg").exists())
        self.assertFalse((hooks / "clonamic-strip-ai-trailers").exists())

    def test_foreign_hook_is_not_replaced(self):
        hook = self.repo / ".git" / "hooks" / "commit-msg"
        hook.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        proc = self.run_script(INSTALL)
        self.assertEqual(1, proc.returncode)
        self.assertEqual("#!/bin/sh\nexit 0\n", hook.read_text(encoding="utf-8"))
        self.assertIn("git rev-parse --git-path hooks", proc.stderr)

    def test_shared_hooks_path_is_refused(self):
        self.git("config", "core.hooksPath", ".husky")
        self.assertEqual(1, self.run_script(INSTALL).returncode)
        self.assertFalse((self.repo / ".husky").exists())


if __name__ == "__main__":
    unittest.main()
